# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='num_ratings',
        ),
        migrations.AlterField(
            model_name='location',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
