# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 09:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLocation',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('name', models.CharField(max_length=64)),
                ('is_free', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=0.0)),
                ('male', models.BooleanField(default=True)),
                ('female', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical location',
                'get_latest_by': 'history_date',
                'ordering': ('-history_date', '-history_id'),
            },
        ),
        migrations.RenameField(
            model_name='location',
            old_name='lat_coord',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='long_coord',
            new_name='longitude',
        ),
        migrations.AddField(
            model_name='location',
            name='female',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='flags',
            field=models.ManyToManyField(blank=True, related_name='flagged_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='male',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
    ]
