# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 11:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20160102_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallocation',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 1, 2, 11, 30, 58, 668102, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 2, 11, 31, 6, 285669, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicallocation',
            name='latitude',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicallocation',
            name='longitude',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(db_index=True),
        ),
    ]
