# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20160102_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallocation',
            name='is_anonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='is_anonymous',
            field=models.BooleanField(default=True),
        ),
    ]
