# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20160103_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallocation',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
