# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 11:31
from __future__ import unicode_literals

import core.methods
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(upload_to=core.methods.file_uploader),
        ),
    ]
