# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20160105_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ban',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='minus_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plus_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Trusted'), (5, 'Super')], default=1, null=True),
        ),
    ]
