# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20160305_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='ban',
            new_name='is_banned',
        ),
    ]
