# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_picture_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='visibility',
        ),
    ]
